### ISSUE TITLE
Finish configuring all the mutations for Harvestcraft plants

### ISSUE THREAD

**Issue by tungstonminer** [tungstonminer/brunel-3#1]

**Comment by GnarlyOldGuy** [comment]
Where would I find a list of the vanilla plants, if there is one?

**Comment by tungstonminer** [comment]
There isn't an easy way to generate one, unfortunately.  However, if you peek in `/config/agricraft/json/defaults/vanilla/plants`, you can see the full list I've already put together.

**Comment by GnarlyOldGuy** [comment]
Just a note to self at this point, harvestcraft:candleberry_plant was not on the horticulture.png file, it was in agricraft.xlxs, but with a slightly different set of parents, blackberry instead of the raspberry in the config file.

**Comment by GnarlyOldGuy** [comment]
OK, starting to run into more discrepancies, which document is the authority document?  The .xlxs or .png file?

**Comment by tungstonminer** [comment]
Go with the image for now.  I made a few changes, but very few.  I’ll post a more authoritative version later tonight.

**Comment by GnarlyOldGuy** [comment]
OK, and one more, because I'm learning and finding, with the exception of true minecraft vanilla plants, there should be a vanilla config file in the vanilla directory?

**Comment by tungstonminer** [comment]
I’m not sure what you’re asking...  *every* plant must have a `_plant.json` file, and anything which is obtained by cross-breeding must also have a mutation file.

**Comment by GnarlyOldGuy** [comment]
OK, finished these and set all of the "chance" variables to 0.5, but in retrospect, we may want to set them to 1 or 0.99 for testing purposes to make sure all of the mutations work and then set them back to random variables or ???.
I had noticed that on some you had set the variable to something other than 0.5, so we could go back and play with these numbers to make the mutations a little more random.
