### ISSUE TITLE
Figure out the remaining Agricraft mutations

### ISSUE THREAD

**Issue by tungstonminer** [tungstonminer/brunel-3#127]

**Comment by tungstonminer** [comment]
I've got the mutations figured out, with the OmniGraffle doc and a PDF version of the same in the `/assets` directory.  Over to @GnarlyOldGuy to enter the mutations in the data file.

**Comment by GnarlyOldGuy** [comment]
Mutations files updated based on the new mutations graphic.

**Comment by tungstonminer** [comment]
I've started to look things over and was confused that while *some* of the updates obviously came through, there were still many plants without mutations.  Eventually I figured out it's because none of the mutations which were in the original set had been enabled!  Fixed that up, and things seem to be good now.  Just doing one final pass through...
