### ISSUE TITLE
The steel gear recipe only accepts Immersive Engineering iron ingots.

### ISSUE THREAD

**Issue by GnarlyOldGuy** [tungstonminer/brunel-3#159]

**Comment by tungstonminer** [comment]
I'm guessing you mean "steel ingots" here, but in any case, that's as it should be.  *Any* metal ingot can be crafted to the correct canonical ingot by placing it in a crafting table.  From there, you should be able to use it in whatever recipe you like.  

However... it's actually a bit cheaper to make gears on the metal press: no bushings required.
