### ISSUE TITLE
Double-check recipes for Pam's machines

### ISSUE THREAD

**Issue by GnarlyOldGuy** [tungstonminer/brunel-3#17]
e.g., distiller

**Comment by tungstonminer** [comment]
I've found a mod which allows CraftTweaker modifications to those machines, so we should be able to adjust things as we find necesary.  In particular, I think we ought to remove any recipes which are already covered by the Industrial Squeezer, etc. and make sure that the output from Pam's machines is reasonable given that they are basically "free" in terms of power or other inputs.
