### ISSUE TITLE
Remove Forestry Squeezer and Fermenter after copying all those recipes over to the IE equivalents

### ISSUE THREAD

**Issue by GnarlyOldGuy** [tungstonminer/brunel-3#20]

**Comment by GnarlyOldGuy** [comment]
I looked at the common.cfg file under forestry and the Fermenter and Squeezer were excluded from the machines section of the code.  
I didn't see a zenscript that dealt with Forestry items, which file in the scripts section would this be addressed in?

**Comment by tungstonminer** [comment]
As you noticed, I already got around to the machine, themselves.  I don't believe there's a ZenScript for Forestry stuff yet, so feel free to just make a new one in the `scripts` directory.

**Comment by tungstonminer** [comment]
You may need to add the machines *back in* so that you can see what recipes they support.  The easiest way is to use JEI to bring up any old recipe, and then click on the title at the top of that dialog.  This will bring you to a place which shows *every single recipe* in the entire game.  From there, you can click the left/right buttons to find the various Forestry machines to see all the recipes for those machines.

**Comment by GnarlyOldGuy** [comment]
Do we want to add all the machines back into the common file to see which recipes we need to move/add/disable?

**Comment by tungstonminer** [comment]
Make sense.

**Comment by GnarlyOldGuy** [comment]
So, I pulled up the Squeezer in JEI, it has 242 recipes associated with it.  The Fermenter has 760 Recipes associated with it, this could be rather challenging unless we can figure out a way to generate the actual item from the mod to assist with the development.

**Comment by tungstonminer** [comment]
Hmm.  That will require some strategizing.  I'll have a look and see if I can think of something.

**Comment by GnarlyOldGuy** [comment]
Here are the major (?) differences between the IE Squeezer and the Forestry Squeezer.

1. Forestry Squeezer is a simple machine, single block.  IE is a Multi-Block machine, more resource-intensive.
2. Forestry Squeezer has 242 recipes, the IE Squeezer has 8 recipes.
3. Forestry squeezer allows the creation of seed oil, fruit juice, honey and various other liquids based on the can (Forestry item) used.  IE Squeezer creates plant oil, honey, and a coke item.

**Comment by tungstonminer** [comment]
Yup!  I've been looking into that as well (take note of the change of assignees).  I think the best strategy is to use ZenScript to add reasonable recipes for the various "target fluids" from the Forestry Squeezer into the IE squeezer.  Fortunately, nearly all of the recipes in the former are easily handled using the ore dictionary.  I'm already partway through implementing a solution.

**Comment by GnarlyOldGuy** [comment]
Here are the major (?) differences between the IE Fermenter and the Forestry Fermenter.

1. Forestry Fermenter is a simple machine, single block.  IE is a Multi-Block machine, more resource-intensive.
2. Forestry Fermenter has 760 recipes, the IE Fermenter has 4 recipes.
3. Forestry Fermenter allows for wider use of materials to create biomass and mead. IE Fermenter has a vary narrow material list to create ethanol.

**Comment by GnarlyOldGuy** [comment]
OK, so you were ahead of me on that.

**Comment by tungstonminer** [comment]
After playing around with this a bit, I think the better course of action is to just leave things alone.  The Squeezer and Fermenter from Foestry don't actually have a ton in common with their counter-parts in Immersive Engineering: even to the point that they don't have compatible slots for inputs and outputs.  So, I think the easiest course of action is to just leave them both alone.

**Comment by tungstonminer** [comment]
Actually...  I think there's a decent way to do this.  Most of the receipes for the Squeezer can be moved to the Industrial Squeezer, and most of the recipes for the Fermenter can be moved to the Mixer.

**Comment by tungstonminer** [comment]
In the end, I was able to remove the Fermenter by transferring all its recipes to the IE Mixer.  I kept the Squeezer, but moved almost all of its recipes over to the IE Industrial Squeezer.
