### ISSUE TITLE
Explore balancing the Charset redstone cabling with regular redstone.

### ISSUE THREAD

**Issue by GnarlyOldGuy** [tungstonminer/brunel-3#204]
A redstone signal is transmitted across a single block with a single piece of redstone dust.  To match that with the Charset mod items it takes 4 times as much redstone and a copper ingot.  This seems a little out of balance.
Yes, the cable will transmit the signal further, but at that high a cost?
I would suggest 2 pieces of redstone dust and perhaps a copper nugget for a single piece of redstone cable.
For insulated cable, maybe add cotton or hemp to the recipe along with a single piece of dye to get the color you desire.

**Comment by tungstonminer** [comment]
I was having exactly the same thought, myself.  I was thinking that a single redstone and copper ingot would be plenty.

**Comment by GnarlyOldGuy** [comment]
Let me explain the thought, redstone dust has a range of 15 blocks before it's signal is lost.  The Charset cable doesn't have any loss from running it a long way, but how often are you going to run it much further than maybe 30 blocks?  So, two pieces of redstone to cover that, the connections would potentially be copper, but you wouldn't need an ingot to make those connections, just small bits of copper, thus a nugget.  The rest sort of follows along the same thought process.

**Comment by tungstonminer** [comment]
There are already several cables in the modpack, including at least one from I.E. which is literally the redstone cabling we used in the powerhouse.  I was thinking of some recipe along those lines, but a bit beefier.  I haven't given it a ton of though as yet.  ;-)

**Comment by tungstonminer** [comment]
Done.
