### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by DerOktopus** [tungstonminer/brunel-3#210]
### Please answer the following questions

*What is your experience playing modded Minecraft?*

I've been playing various modpacks throughout the years, mainly adventure, automation, and some tech. 

*Have you successfully been able to play the modpack in single-player?*

Yes, I was able to run the modpack without any problems. 

*What is your Minecraft username?*

DerOktopus

### Please re-state the server rules in your own words

1. No random or uncalled for player vs. player combat
2. If it's made by another player, leave it alone
3. Don't build in the vicinity of another player or anywhere too near them without asking for their permission
4.  Build structures or machines that can be easily identified by other players
5. Only landscape if something meaningful is coming out from it. 

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You should be all set!  Welcome!
