### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by Maiesa** [tungstonminer/brunel-3#211]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
I've been playing modded MC on and off since 2012

*Have you successfully been able to play the modpack in single-player?*
I have not played it, but I did download the modpack and load a single-player world with no issues. 

*What is your Minecraft username?*
Maiesa

### Please re-state the server rules in your own words
Respect other players builds/items, don't engage in PVP without consent, be mindful of the proximity of other player builds, don't destroy the terrain unless it's with the intent on making something of it, make your builds easily identifiable and last but not least, respect other players. Thanks!
### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You should be all set!  Welcome!
