### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by foehammer89** [tungstonminer/brunel-3#212]
### Please answer the following questions

*What is your experience playing modded Minecraft?* Moderate, lately I’ve been playing MC eternal and I’m looking for something different. 

*Have you successfully been able to play the modpack in single-player?* I’ve been able to load a single player world, but I haven’t played on that world. 

*What is your Minecraft username?*
Foehammer89

### Please re-state the server rules in your own words

Respect all players and their builds/belongings. Don’t build too close to other players, don’t destroy the terrain unless you’re planning on making something of it. No pvp unless it’s agreed by all parties and mark your builds somehow so other players are able to identify who it belongs to. 

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You should be all set!  Welcome!
