### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by M1CAB** [tungstonminer/brunel-3#213]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
I've been playing modded minecraft for a few years, I started out playing war servers/modded factions, and modpacks like crazy craft with some friends. More recently I have been playing some more challenging packs like e2e and po3 kappa. In general, I mostly play tech packs, I tend to find the automation aspect fun. 
*Have you successfully been able to play the modpack in single-player?*
Yes.
*What is your Minecraft username?*
Dominqtor131
### Please re-state the server rules in your own words
No unconsented pvp, don't build too close to other people without permission, don't grief, make it clear that you have built something so people know, don't destroy landscapes unless planning to build something nicer on it. 
### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You should be all set!  Welcome!
