### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by Levanon** [tungstonminer/brunel-3#214]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
I have been playing modded minecraft since 1.6

*Have you successfully been able to play the modpack in single-player?*
Yes

*What is your Minecraft username?*
Levanon

### Please re-state the server rules in your own words
No pvp. Respect other players' builds and the natural landscape. Ask before building near other players. Use signs

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You should be all set!  Welcome!
