### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by starwolfkon** [tungstonminer/brunel-3#215]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
I really enjoy it, I have mostly played singleplayer modpacks though.

*Have you successfully been able to play the modpack in single-player?*
I have not I figured I learn it along other people, sounds much more fun too to be honest

*What is your Minecraft username?*
StarWolfKon

### Please re-state the server rules in your own words
Dont be a dick to other people and enjoy the game I guess.

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
Could you be a bit more specific in your re-statement of the server rules?  We have a few specific things we have in mind which are different from many other servers.  I only ask to make sure there are no misunderstandings down the road.  Thanks!
