### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by xdorito** [tungstonminer/brunel-3#216]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
Playing off an on through out the past 4 years. Generally play Expert style packs or progression ones with communities all working towards goals.

*Have you successfully been able to play the modpack in single-player?*
Yep!

*What is your Minecraft username?*
xDorito

### Please re-state the server rules in your own words
Be nice
No ask? No hit.
Leave what isn't nature as you found it
Be a friendly consenting neighbor not an eye sore
Be obvious that you're building something
Make something better of disturbed nature

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by andrewminer** [comment]
You should be all set!  Welcome to the server!

**Comment by tungstonminer** [comment]
You should be all set.  Welcome!
