### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by wkosmos** [tungstonminer/brunel-3#217]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
Been playing exclusively modded since the golden age of 1.7.10 when Witchery still existed.

*Have you successfully been able to play the modpack in single-player?*
Yup. Seems to run fine other than AgriCraft bugging me to write JSON files for them.

*What is your Minecraft username?*
`NeddieSeagoon`

### Please re-state the server rules in your own words
Don't be a dick, don't touch stuff that isn't yours (including line of sight/views), consensual PvP only, don't wreck the landscape, don't build stuff that isn't visibly built (unless you don't care if people touch it).

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You're all set!  Welcome to the server!
