### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by KnedlikMCPE** [tungstonminer/brunel-3#218]
### Please answer the following questions

*What is your experience playing modded Minecraft?
I know basically just Mekanism and BuildCraft, but I'd like to learn more.
*Have you successfully been able to play the modpack in single-player?*
Yes.
*What is your Minecraft username?*
KnedlikTrain
### Please re-state the server rules in your own words
- Don't destroy anything made by other players
- PVP only if the other person wants it
- Make sure others know you made the things you made
- If building close to another player, talk with them about it first and make sure they don't have a problem with it.
- Don't destroy the nature, use it to your advantage and
### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You're all set!  Welcome to the server!
