### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by LotusRayne** [tungstonminer/brunel-3#223]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
I play modded pretty offen.

*Have you successfully been able to play the modpack in single-player?*
Havent tried yet but im sure i can run it.

*What is your Minecraft username?*
Lotus2506

### Please re-state the server rules in your own words
DOnt desroy things that are not yours, dont just randomly fight people its rude, ask to build near people if you want to live near somone.

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
Hello Lotus!  You're still on the list, so you can log in any time.  😄
