### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by minioof** [tungstonminer/brunel-3#225]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
i play a lot of modded minecraft (7 days playtime on E2E, 2.5 days playtime on valhelsia 2 also i finished caveblock) and i really enjoy it.

*Have you successfully been able to play the modpack in single-player?*
yes

*What is your Minecraft username?*
minioof

### Please re-state the server rules in your own words
1. be a nice person
2. no pvp unless the other person agreed to it
3. do not grief/steal
4. do not build on other people's land unless they allow u to
5. when u finish your cool building u can let other players know about it
6. do not destroy the land if you dont build something nice

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You're all set!  Enjoy!
