### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by 70c701** [tungstonminer/brunel-3#226]
### Please answer the following questions

*What is your experience playing modded Minecraft?* Have been playing modded Minecraft since 2013, when I got pretty bored of the normal playthrough. Enjoy the grind became the slogan.

*Have you successfully been able to play the mod pack in single-player?* Have not played through the Brunel III mod pack in single-player yet, because this is my first time seeing the mod pack.

*What is your Minecraft username?* 70c

### Please re-state the server rules in your own words
 Treat everyone how you'd want them to treat you, ask for a duel with someone you just met, if you didn't make it you probably shouldn't touch it, get a builder's permit before building your house in someone's backyard, put your name on EVERYTHING that you build, and respect nature.
### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You're all set!  Enjoy!
