### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by Kleinjan43** [tungstonminer/brunel-3#228]
### Please answer the following questions

*What is your experience playing modded Minecraft?*

I have played modded minecraft on and off for many years, having played mostly on servers as I enjoy playing with others. I prefer to play tech mods and Immersive engineering is my favourite.

*Have you successfully been able to play the modpack in single-player?*

I have been able to load the modpack on singleplayer.

*What is your Minecraft username?*

Treaclebeard

### Please re-state the server rules in your own words

Be nice to everyone and do not disturb anything built by other players unless permission is given. Dont build to close to other players and dont destroy the landscape without making it look nicer. Also no unwanted PvP

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You should be all set!  Welcome!
