### ISSUE TITLE
Disable the greenhouse from Forestry

### ISSUE THREAD

**Issue by GnarlyOldGuy** [tungstonminer/brunel-3#23]

**Comment by tungstonminer** [comment]
So far as I can tell, this is a defunct part of the mod, but the related items still show up in JEI.  So, I think all that needs to be done here is to just remove those items so they don't confuse things.

**Comment by GnarlyOldGuy** [comment]
I've done this in the remove_recipes script and tested it locally.  This can be closed.

**Comment by tungstonminer** [comment]
Hmm.  I've already got code for this in place.  I'll pick one solution and discard the other, and then close the issue.   I'm assuming you opportunistically saw the need to remove this stuff and went ahead.  In general, when an issue is assigned to someone, it's best to assume that they may have already finished that work, and to check with them before starting to work on it.

**Comment by GnarlyOldGuy** [comment]
Oops, my apologies . . .

**Comment by tungstonminer** [comment]
No worries!  New tools, new protocols to learn.  ;-)

**Comment by tungstonminer** [comment]
I've pushed up my changes, but there wasn't anything to pull down.  So, when you next pull changes, just remove the bit from the `remove_recipes.zs` script and let the part I added in `forestry.zs` do the work.
