### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by JStanWade** [tungstonminer/brunel-3#231]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
A couple years playing various mods, but never fully completing any due to lack of interest from friends/lack of having people to play with.

*Have you successfully been able to play the modpack in single-player?*
I have gotten to the point of exploring other biomes and growing food. I will have no problem going forward. (I played an hour before writing this)

*What is your Minecraft username?*
Visored97

### Please re-state the server rules in your own words
Don't be an a-hole

Don't murder people, but agreed upon duels are fine

Not yours, don't touch

Don't ruin someone's build by building next to them and ruining the view, without permission of course

Don't really understand this one but either - Put yo name on it so people can see what you made OR Don't make secret builds no one can view

If you mess it up, you clean it up (Landscape)
### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You're all set!  Welcome!
