### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by tatertotskk** [tungstonminer/brunel-3#235]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
i have a alot
*Have you successfully been able to play the modpack in single-player?*
yup
*What is your Minecraft username?*
tatertotskk
### Please re-state the server rules in your own words
be nice
dont steal
no pvp unless you ask and they say yes
not greifing or stealing of any kind
make sure people know whats urs
and do not miss up areas
### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You're all set!  Welcome!
