### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by JoshyDon** [tungstonminer/brunel-3#238]
### Please answer the following questions

*What is your experience playing modded Minecraft?*

I am a Minecraft veteran with 6+ years of Minecraft under my belt. I am moderately experienced in modded Minecraft and whatever I can't figure out I can find sources to help me.

*Have you successfully been able to play the modpack in single-player?*

As I have a good gaming laptop, I can play every type of modpack no matter the amount of mods.

*What is your Minecraft username?*

DanPlayzV3

### Please re-state the server rules in your own words

No random PVP
Do not Grief
No random building within another individual's area
Make buildings simple for other players
Improve the area you build at

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You're all set! Welcome!
