### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by spunkiethefirst** [tungstonminer/brunel-3#239]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
Been playing modded since tekkit and technic back when yogscast was making it popular.

*Have you successfully been able to play the modpack in single-player?*
Yes

*What is your Minecraft username?*
spunkiethefirst

### Please re-state the server rules in your own words
-PvP only by agreement between participants
-Do not tamper with others creations
-No building within sight of another players creations unless agreement is reached previously
-Builds should be obvious to other players to avoid issue with "disturbing other players builds rule"
-Do not leave the terrain like a wither ran through it

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You're all set!  Welcome!
