### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by 9arriflex9** [tungstonminer/brunel-3#240]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
i played alot of modded mc over the years big fan of ftb packs would be my firsttime trying testing anything based on rails/machinery mods.

*Have you successfully been able to play the modpack in single-player?*
yes but i always prefer to see other people creation

*What is your Minecraft username?*
Arriflex

### Please re-state the server rules in your own words
be nice, don't mess with other people build

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You're all set!  Welcome!
