### ISSUE TITLE
Sleeping in an Animania covered wagon does not restore health

### ISSUE THREAD

**Issue by spunkiethefirst** [tungstonminer/brunel-3#242]
Would it be possible to make sleeping in an Animania covered wagon restore health in the same way sleeping in a bed does?

Sleeping bags and bed carts do not have the same issue.

**Comment by tungstonminer** [comment]
I'm afraid there isn't anything I can do to address that issue.  However...  only player(s) who actually sleep get a health benefit.  That is, if you weren't one of the ones Morpheus tallied toward the sleep count, you won't get healed.  At the moment, Morpheus only needs a single player to sleep, so if you weren't the very first place to sleep, you don't heal.  Therefore, I'd recommend doing a trial.  When you're hurt, ask the other players *not* to sleep so you can be sure you're one Morpheus sees as sleeping.  Then, you can determine whether or not there's any difference between sleeping in a regular bed vs sleeping in the wagon.
