### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by AnfedigA** [tungstonminer/brunel-3#244]
Hi.
### Please answer the following questions

*What is your experience playing modded Minecraft?*
I've Been Playing Modded Minecraft Since 1.7.10 Was released.
*Have you successfully been able to play the modpack in single-player?*

*What is your Minecraft username?*
AnfedigA
### Please re-state the server rules in your own words
Dont Be Stupid, Keep it Nice.
### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
> Dont Be Stupid, Keep it Nice.

I'm afraid I'm going to have to ask you to elaborate a bit more than that.  We need to make sure you understand things fully.

**Comment by AnfedigA** [comment]
Be Kind, Dont Do PvP Without Consent, Dont Destroy/modify Payer Buildings, Dont Build Near A Player Construction Without his consent, Dont Broke The landscae If ur not gonna build anything that looks Better.

Hope This will be enough.

Thanks For your Time

**Comment by tungstonminer** [comment]
That's great, thanks!  You should be all set.  Welcome to the server!
