### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by ROOTTOOT** [tungstonminer/brunel-3#245]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
Played on two heavily modded servers before, one of which i got bored of because it had extreme recipe requirements for some reason, the other one got shut down. Also played some maybe 10 hours on singleplayer using mossynet modpack which im pretty sure is gone now. *Have you successfully been able to play the modpack in single-player?*
yes 
*What is your Minecraft username?*
ROOT_TOOT
But im named Cheesecake_ on discord, cus i forgot my password

### Please re-state the server rules in your own words
Don't be a dick, no unwilling pvp, no destroying  other people's buildings or land, dont build near others without their permission, put some signs so people know you built that stuff

**Comment by tungstonminer** [comment]
You're all set! Welcome to the server!
