### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by Raphyol** [tungstonminer/brunel-3#246]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
I have a lot of experience with automation and with a ton of mode
*Have you successfully been able to play the modpack in single-player?*
Playing Modpacks in singleplayer is usually harder than on a server because the chunkloading is up to the hosting and not the client. but it works

*What is your Minecraft username?*
Raphyol

### Please re-state the server rules in your own words
no PVP without both people accepting it.
No Griefing
not building anywhere near others
Signing everything i made so they see its mine
No Big Chunkmining/excavating
### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
You're all set!  Welcome to the server!
