### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by ManWithMustash** [tungstonminer/brunel-3#273]
### Please answer the following questions

*What is your experience playing modded Minecraft?* I have been playing modded Minecraft for a few years. From one genre to another genre.

*Have you successfully been able to play the modpack in single-player?* Yes, I started a creative world, when I loaded in I had lag because the chunks were loading, but no more lag spikes happened.

*What is your Minecraft username?* YT_TarantulaOP

### Please re-state the server rules in your own words
1. You can fight with others player only if they allow it.
2. Do not break and/or build in builds you don't own.
3. Make sure other players know the build's owner.
4. Don't destroy the landscape unless very needed.

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
Well... good news and bad news.  The bad news is that the Brunel 3 server will be shutting down in the near future since everyone has gotten tired of playing the Brunel modpack (this is our 3rd iteration on it now).  The good news is that we will be starting a new server with  the [Istari](https://github.com/tungstonminer/istari) modpack *TOMORROW* at 15:00 GMT.  Would that suit you, instead?

**Comment by ManWithMustash** [comment]
Yes, Indeed. Sorry for not replying, Personal reasons made me forget...
