### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by smokismoki** [tungstonminer/brunel-3#274]
### Please answer the following questions

*What is your experience playing modded Minecraft?*

*Have you successfully been able to play the modpack in single-player?*
Yes, I have
*What is your Minecraft username?*
Breakdown_Brkdwn
### Please re-state the server rules in your own words
Don't be an ass, be nice
No non-consentual PVP
Don't touch other player's stuff
Don't Build Near other People
Don't tear up the land for no reason
### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`brunel3.tungstonminer.com`

You may also find it helpful to view [the world map](http://brunel3.tungstonminer.com:8123) to get acquainted with what has been done already.

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/brunel-3/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.

**Comment by tungstonminer** [comment]
Sorry to disappoint, but the Brunel 3 server has been shut down for a while now.  If you're interested in my current server, [Istari](https://github.com/tungstonminer/istari/wiki), you're welcome to copy your application [over here](https://github.com/tungstonminer/istari/issues/new?assignees=GnarlyOldGuy&labels=&template=server-access-request.md&title=Server+Access+Request).  Sorry to ask you to copy it over, but here's a different mod who handles applications on that server.
