### ISSUE TITLE
Make Horse Power worthwhile

### ISSUE THREAD

**Issue by AndMattBurt** [tungstonminer/brunel-3#32]
balance outputs vs crafting and later machines to increase usefulness

**Comment by tungstonminer** [comment]
I think I'm going to leave HorsePower's recipes as they are.  I think the benefit is that they allow you to automate production very early game: not that they allow you to get more benefit.  The trouble is that if you increase the benefit in the recipes for these machines, you'd have to increase the benefits *even more* for using the more complex machines which come later in the tech tree.
