### ISSUE TITLE
Hide all spawn eggs from JEI

### ISSUE THREAD

**Issue by tungstonminer** [tungstonminer/brunel-3#34]

**Comment by GnarlyOldGuy** [comment]
OK, so, I'm going to take this one on.  I've done a real quick test on the local script on my standalone and I have a part of it working for the Animania Spawn Eggs, mainly because they are defined individually.  The Minecraft and Better Animals Spawn Eggs are not defined the same way though, minecraft:spawn_egg, and the same for Better Animals, except the beginning of course.  They do all have an individual number associated, but I'm not sure how to incorporate that into the exclusion code and the API doc is not that refreshing on this point.  Suggestion/help on this one?

**Comment by tungstonminer** [comment]
Take a look at: https://github.com/tungstonminer/ad-astra/blob/master/scripts/01_remove_recipes.zs#L56

**Comment by tungstonminer** [comment]
You'll need to make sure to "declare" the `ids` variable, too: https://github.com/tungstonminer/ad-astra/blob/master/scripts/01_remove_recipes.zs#L5

**Comment by GnarlyOldGuy** [comment]
OK, all of the spawn eggs for Animania are excluded with the exception of the random generations spawn eggs.

I'm not sure how to identify the IDs for the minecraft spawn eggs and the better animal spawn eggs.  The research I did found that the way to identify these has changed over the past versions and it looks like it takes more than just an ID, but I'm not sure and maybe you know a better way to find this info, it doesn't show in the tooltip.

Thoughts or assistance?

**Comment by tungstonminer** [comment]
There are two tools to help identify things in-game.  First, Minecraft has a ton of different [debug keys](https://minecraft.gamepedia.com/Debug_screen#More_debug-keys) which allow you to turn on/off various extra bits of data.  The one you most want right now is `F3-H` (press `H` while holding `F3`).  That will turn on/off the IDs of items when you hover over them in your inventory.

Second, if you want to see exactly how to get a particular item in a CraftTweaker script, grab the item in question, drop it in your hotbar, and select it so that it's in your character's hand.  Then execute the command: `/mt hand`.  This will print out exactly the ZenScript you'd need to get exactly that item.  Most importantly, this *includes the tags*.  So, a spawn egg for a cow yields: `<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:cow"}})`.  Even more handy, if you click on the text, it will copy it to your clipboard.

Since spawn eggs are all `<minecraft:spawn_egg>` with various NBT tags applied to them, my first guess is that you can hide all the vanilla and BetterAnimalsPlus eggs just by hiding `<minecraft:spawn_egg>`.

**Comment by GnarlyOldGuy** [comment]
I look a little deeper into what you suggest.  I tried the last one, just doing the <minecraft:spawn_egg> and it gave me an in game error message on start.  No bueno . . .

**Comment by tungstonminer** [comment]
Hmm.  That's disappointing.  What code did you use to hide them, and what was the error?  Might be something I've run into before...

**Comment by GnarlyOldGuy** [comment]
I used _JEI.removeAndHide(<minecraft:spawn_egg>);_
and a correction, nothing was removed, so that little bit of code was not going to do it.

**Comment by tungstonminer** [comment]
Gotcha.  I assume you mean: `JEI.removeAndHide(<minecraft:spawn_egg>);`, but yeah, I suppose that would be too easy.  I think your best bet will be to use the `/mt hand` command to get a sense of how the tags work, and then sent up an array of animal names and loop through them to get the `IItemStack` you need.  Something like:
```
var animalNames = [
    "cow", "pig", ...
] as string[];
for animalName in animalNames {
    JEI.removeAndHide(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:" ~ animalName}});
}
```

**Comment by GnarlyOldGuy** [comment]
I'll give it a shot with the `/mt hand` command and see what it comes up with.  I tried a single line to check out the `JEI.removeAndHide(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:cow"}});`syntax and it generated an error message on start, need to remember to copy those, it might just be a clue.

**Comment by tungstonminer** [comment]
Hmm.  Double check with `/mt syntax` prior to restarting the game each time you make a change.  Unfortunately, changes to the ZenScripts won't actually take effect until you restart the game, but that will at least give you any feedback about bad syntax.

**Comment by GnarlyOldGuy** [comment]
I know, I think I've restarted the game about 20 times today while testing changes.
The error message is `ERROR: [crafttweaker | SIDE_CLIENT]: Error parsing 02_remove_recipe.zs:45 -- : expected`

**Comment by tungstonminer** [comment]
Ah.  Syntax errors mean that CraftTweaker will just skip the remainder of that one script.  That can make things very confusing as you see *some* of your changes, and assume everything should have worked.  In this case, you seem to be missing a `:` character on line 45.  Those are most commonly used to separate the mod from the item name in an item handler (e.g., `<minecraft:spawn_egg>`), so that's the first thing I'd look for.

**Comment by GnarlyOldGuy** [comment]
OK, yes, it was a syntax error, but it was on line 38, the line with the following code,
`JEI.removeAndHide(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:cow"}}))`
the issue was the missing `;` at the end of the line, derp.
So I added it back in and it works!  I tried it on another single line for the bat spawn egg and it's confirmed.  So now I need to get the whole array of names and see how it goes.  I may try the little bit of code you shared so I don't have to do 100 more individual lines of code, although it may be easy since the code is pretty much cut and paste from the `/mt hand` command and might need to do that for each egg to get the correct code.  I think about it a little.

**Comment by GnarlyOldGuy** [comment]
By any chance did you add Charcoal and Enchantment Table to the remove recipes file? Just want to make sure, the file I was working from did not have those, and I noticed the changes when I went to push the most recent changes.

**Comment by tungstonminer** [comment]
Yes.  The former can be produced by creating a charcoal pile (from Forestry).  The latter was removed because I'm trying to eliminate all magic from the modpack.

**Comment by GnarlyOldGuy** [comment]
I believe this is done, your review is appreciated.
