### ISSUE TITLE
Make sure all fuels are balanced

### ISSUE THREAD

**Issue by tungstonminer** [tungstonminer/brunel-3#35]
The following flammable liquids are created by various mods in the game:

* Forestry
  * Ethanol `<liquid:bio.ethanol>`
  * Biomass `<liquid:biomass>`
* Immersive Engineering
  * Biodiesel `<liquid:biodiesel>`
  * Diesel `<liquid:diesel>`
  * Ethanol `<liquid:ethanol>`
  * Plant Oil `<liquid:plantoil>`
* Immersive Petrolium
  * Crude Oil `<liquid:oil>`
  * Gasoline `<liquid:gasoline>`
  * Lubricant `<liquid:lubricant>`
  * Napalm `<liquid:napalm>`
* Immersive Technology
  * Steam `<liquid:steam>`
* Railcraft
  * Creosote `<liquid:creosote>`
  * Steam `<liquid:steam>`

We should make sure that:

1. they all work in the various machines across the modpack
2. they have energy ouput scaled to the level of effort to create them
3.  they have energy output roughly 10x the cost of production

**Comment by tungstonminer** [comment]
I've at least got a solid set of recipes for all these things in Immersive Engineering machines now, and I've created an `assets/fuels.xlsx` spreadsheet to start some of the calculations of energy efficiency and costs of production for each.

I still want to:

1. finish the spreadsheet with each "line" of fuel production to get an exact sense of relative energy return
2. update the various devices which consume fuel to use appropriate ones of those listen above at reasonable rates of energy production

**Comment by tungstonminer** [comment]
I've made some more progress on the fuel spreadsheet.  At this point, there are a series of formulae which allow you to compute the various costs of producing so much of a certain item (e.g., how many honeycombs and how much RF power do you need to produce a stack of honey drops).  The costs will automatically scale themselves based upon the amount desired (i.e., the number of honeycombs will double if you want two stacks).

At the bottom, there are a few rows which indicate how much power you can produce by burning certain fuels in certain machines.  As with the other formulae, you tell it how much of the output you want (i.e., how much RF power), and it will tell you how much of the inputs you need (i.e., the amount of fuel).  By using connecting the desired output amount of certain formulae (e.g, biodiesel fuel) to the inputs of other (e.g., RF power produced by burning biodiesel fuel), you can work your way backward to figure out how much power gets used for the entire production chain.

Finally, to deal with the idea that gathering raw ingredients costs something, the first few formulae rows specify a "collect" machine whose power requirement is simply a proxy how much the player's effort "costs" in terms of RF.  Collecting saplings is harder than collecting berries, so it has a higher power requirement.

Finally, at the very bottom the are a few lines which tally the energy produced, the energy consumed in producing that power, and provides an overall efficiency for the process (including the gathering of raw materials).

The next step is to pick a bunch of relevant fuel production chains and compare their relative efficiences given the current settings to see if things make sense from an effort/reward point of view.  For example, setting up a fuel production chain using honey & plant matter to produce biomass which is then turned into ethanol, which is combined with plant oil to make biodiesel is quite a lot of work.  It should be, therefore, more efficient in producing power: all things considered.  Currently, it is not.  That's the kind of thing  this issue is meant to address.

**Comment by tungstonminer** [comment]
I've spent a little while playing with the spreadsheet, and here are some of the results:

* I.E. Biodiesel — 86%
  * using only I.E. machines and materials
* Forestry (best case) — 75%
    * regular crops, best fertilizer, fruit juice + I.E. plant oil to make biodiesel
* Diesel + Gasoline — 58%
    * only Immersive Petrolium machines & materials, buring excess gasoline for power
* Forestry (worse case) — 51%
  * saplings, worst fertilizer, water + I.E. plant oil to make biodiesel
* Diesel only — 47%
  * only Immersive Petrolium machines & materials, ignoring excess gasoline
* Diesel + Gasoline (residual) — 8%
    * only Immersive Petrolium machines & materials, buring excess gasoline for power
    * after oil reservior is empty, productivity drops from 15mB/t to 6mB/t, so overall efficiency suffers greatly
* Diesel only (residual) — -3%
  * only Immersive Petrolium machines & materials, ignoring excess gasoline
  * after oil reservior is empty, productivity drops from 15mB/t to 6mB/t, so overall efficiency suffers greatly
* Gasoline only — -374%
  * only Immersive Petrolium machines & materials, ignoring excess diesel
  * uses portable generator, which only generates 256RF/5mB of gasoline (the diesel generator is 10x as efficient)
  * net negative power!  It costs more to refine than the fuel produces in the portable generator
* Gasoline only (residual) — -819%
  * after oil reservior is empty, productivity drops from 15mB/t to 6mB/t, so overall efficiency suffers greatly
  * only Immersive Petrolium machines & materials, ignoring excess diesel
  * uses portable generator, which only generates 256RF/5mB of gasoline (the diesel generator is 10x as efficient)
  * net negative power!  It costs more to refine than the fuel produces in the portable generator

This doesn't exactly give me the results I was hoping for, based upon the level of effort to set up each solution.  I was hoping to see something more like this, instead:

* Diesel + Gasoline
* Diesel only
* Forestry (best case)
* I.E. Biodiesel
* Forestry (worse case)
* Diesel + Gasoline (residual)
* Diesel only (residual)
* Gasoline only
* Gasoline only (residual)

One thing that stands out is that the Immersive Petrolium Distillation Tower is quite expensive, and that lowers the efficiency of the Diesel-based and Forestry-based soltuions quite a bit.  I'll look at what playing with the costs there does to the overall picture.  Perhaps that will be sufficient to re-arrange the list as I'd like.

**Comment by tungstonminer** [comment]
The more a think about this, the more convinced I am that: 1) it could take a while to really fine-tune things, and 2) fine-tuning is definitely *not* necessary prior to starting playtesting.  I think it's clearly *close enough* to done, that we can move on to other things and come back to this later.

**Comment by GnarlyOldGuy** [comment]
Agreed, I think there are many of these that will require playtesting or just release, and then modification after we get some experience on the server to see what the balance is.

**Comment by GnarlyOldGuy** [comment]
So, I was still curious about this and recalled that you had been working on this prior to the last release.  One of the things I was most furious about was the energy content or calorific content of the various fuels and how we more realistically model those in the mod if that's important.
So I went to this website [https://www.engineeringtoolbox.com/fossil-fuels-energy-content-d_1298.html] to have a look.  The list is pretty extensive and I was surprised how close some of the fuels are to energy content relative to how they are modeled in the mod pack.
For instance, just looking at the regular fuels and the gross heating value you get;
Crude Oil      19580 Btu/lb
Gasoline       20007 Btu/lb
Conv Diesel  19676 Btu/lb
Bio-Diesel     17269 Btu/lb (listed as Methyl ester)
Ethanol         12832 Btu/lb
Coal              10304 Btu/lb (wet basis)
Coking Coal  12840 Btu/lb (wet basis)
Charcoal       14918 Btu/lb (wood)
Wood           8126 - 8899 Btu/lb (range provided based on the various wood types listed)
Some surprising numbers.  Gives you the idea that the modeling in the various mods is well off on the heat content given when used.  I know you were more concerned with the heat content versus the cost of production and materials to be able to process, but when you start to look at these, we may want to consider balancing these with more realistic numbers after considering the cost of production.  No one processes fuel for energy consumption unless it pays a dividend.

**Comment by tungstonminer** [comment]
Fascinating!  I'm totally down for adjusting the fuel values for things to be more realistic.  The thing that still needs figuring out is exactly how to translate this information into terms the game can understand.  Here are a few examples:

* [Furnace](https://docs.blamejared.com/1.12/en/Vanilla/Recipes/Furnace/Recipes_Furnace/#fuel)—you can set the "burn time" of a fuel object in ticks (10 ticks per item "cooked" / "smelted")
* [Fluid Boiler](https://bitbucket.org/noeppi_noeppi/moretweaker/wiki/Railcraft.md)—you can set the heat / bucket, which relates to turning water into steam via a [complex calculation](https://calculator.towerofawesome.org/?sP=0&rE=0&rE=1&fPSM=1&t=16&nT=1&h=500&e=SteamMB&fT=0&cF=1000&m=0&hP=0&rP=0&cP=0&B1=0&B2=1&hP=1&rP=1&cP=1#).
* Solid Fuel Boiler—I believe uses the same values as the furnace.
* [Diesel Generator](https://docs.blamejared.com/1.12/en/Mods/Immersive_Engineering/CraftTweaker_Support/Diesel_Helper/)—Can be configured with various fuels by giving the time (in ticks) a bucket of that fuel will last in a running gneerator producing 4096 RF/t.

So... if you're keen to do the math, I'd be happy to check your work!

A few further thoughts:

* What other things can be burned, and what energy values should *they* have?  (e.g., sticks, slabs, stairs, ladders, etc.)
* Do we differentiate between I.E. ethanol vs Forestry ethanol?  If not, they we should probably remove one or the other.
* Where does creosote fit in your chart?
* Can any machine burn any liquid fuel?  If not, which ones can burn what?
* Where does lava fit into this?  Railcraft lets the *solid fuel boiler* use lava buckets as input, but *does not* allow liquid lava in the fluid boiler **on purpose**.
* What concessions, if any, would we want to make because *this is a game*?  If something difficult to do without any payoff, it probably doesn't even belong in the game *at all*.

**Comment by tungstonminer** [comment]
Once you have all those things worked out, the next question is: how much should it cost to run various machines?  For example, the crude oil production line was unreasonably inefficient with the default settings, but is way too fast now.  Unfortunately, the machine seems to use so much energy / tick, so you can't separate the two.

**Comment by GnarlyOldGuy** [comment]
> Fascinating! I'm totally down for adjusting the fuel values for things to be more realistic. The thing that still needs figuring out is exactly how to translate this information into terms the game can understand. Here are a few examples:
> 
> * [Furnace](https://docs.blamejared.com/1.12/en/Vanilla/Recipes/Furnace/Recipes_Furnace/#fuel)—you can set the "burn time" of a fuel object in ticks (10 ticks per item "cooked" / "smelted")
> * [Fluid Boiler](https://bitbucket.org/noeppi_noeppi/moretweaker/wiki/Railcraft.md)—you can set the heat / bucket, which relates to turning water into steam via a [complex calculation](https://calculator.towerofawesome.org/?sP=0&rE=0&rE=1&fPSM=1&t=16&nT=1&h=500&e=SteamMB&fT=0&cF=1000&m=0&hP=0&rP=0&cP=0&B1=0&B2=1&hP=1&rP=1&cP=1#).
> * Solid Fuel Boiler—I believe uses the same values as the furnace.
> * [Diesel Generator](https://docs.blamejared.com/1.12/en/Mods/Immersive_Engineering/CraftTweaker_Support/Diesel_Helper/)—Can be configured with various fuels by giving the time (in ticks) a bucket of that fuel will last in a running gneerator producing 4096 RF/t.
> 
> So... if you're keen to do the math, I'd be happy to check your work!
> 
I think there is a way to achieve a balance from the fuels and equating them to each other based on the energy content.  I need to think about it a little more in order to come up with a conversion factor for the various mods since each one seems to have it's own way of calculating the way energy or fuel is used.  Are you including the IE boiler in the above?  It seems to be missing.

> A few further thoughts:
> 
> * What other things can be burned, and what energy values should _they_ have?  (e.g., sticks, slabs, stairs, ladders, etc.)

For other things that can be burned we may need to think a little more about it, for instance, can sticks really be used to generate enough heat to fuel a high-pressure boiler?  Maybe in a small furnace?  Does it begin to get a little too out of hand?  Maybe we allow someone to put other burnable materials in a coke furnace to create charcoal or whatever based on the type of fuel input?

> * Do we differentiate between I.E. ethanol vs Forestry ethanol?  If not, they we should probably remove one or the other.

Is this something that can be addressed in the ore table so both return the same result when used?

> * Where does creosote fit in your chart?

I was never comfortable with burning creosote, it was always a risk in a wood-fired stove, but I never thought of it as a fuel for heating.  I could be wrong.

> * Can any machine burn any liquid fuel?  If not, which ones can burn what?

I think this is pretty well defined right now in the game mechanics, but we can discuss a little further.

> * Where does lava fit into this?  Railcraft lets the _solid fuel boiler_ use lava buckets as input, but _does not_ allow liquid lava in the fluid boiler **on purpose**.

Excellent question, I was not really comfortable about this one as well from a reality perspective.  It's really difficult to think about this from a use perspective, it goes in as a really hot thick liquid and when it reaches a certain temperature it becomes difficult to deal with, it becomes solid after all!

> * What concessions, if any, would we want to make because _this is a game_?  If something difficult to do without any payoff, it probably doesn't even belong in the game _at all_.

Agree, maybe we establish the reality perspective as closely as possible, and if it looks really stupid on the difficulty scale we tweak it to make it doable in the game.

> * What energy values should be produced by the various _other_ ways to produce power (e.g., windmill, waterwheel, thermoelectric generator)?

Do we really want to go there on this one?  There is such a vast difference in the efficiency of those just against each other (waterwheel and windmill versus thermoelectric) that it could be a whole other set of thing to calculate and get close to real.  The thermal energy contained in uranium versus liquid fuel is HUGE, like megajoules versus piddly joule numbers.

**Comment by tungstonminer** [comment]
> Are you including the IE boiler in the above? It seems to be missing.

No.  I don't know whether I even have access to change that.  We can peek at the configs / CraftTweaker docs to check.

> For other things that can be burned we may need to think a little more about it...

There's not a ton of flexibility for solid fuels.  The *only* thing you can really do is to say how long they burn for, and pretty much everything in the game uses that.

> put other burnable materials in a coke furnace...

I'd be inclined to leave this part as it is.  I'd be surprised to learn that you could successfully make charcoal out of anything other than green logs.  If the wood is too dry, it just burns to ash without leaving any charcoal behind.

>> Where does lava fit into this?
> Excellent question, I was not really comfortable about this one as well...

I agree.  I think for situations which merely require something to be *hot* for a limited time (e.g., a furnace), it's not totally crazy.  However, to expect it to work in a system made of delicate metal valves, etc...  not so much.

> waterwheel and windmill versus thermoelectric

I think the waterwheel and windmill should be scaled to match realistic output compared to burning fuel.  They actually *are* seriously underpowered, and only suitable for small operations, and they should reflect that.

For thermoelectric, I think it's important to realize that we're *not* talking about nuclear fission here... just [one of these](https://en.wikipedia.org/wiki/Thermoelectric_generator).  So, uranium in this case is only valuable because it's *hot*, not because it's *radioactive*.  Of course, it's hot *because* it's radioactive, but that doesn't really matter for this device.  :-)

**Comment by tungstonminer** [comment]
I spent a bunch of time re-balancing things for v2.0.0 of modpack.  I didn't try to change anything to do with the windmill, waterwheel, or TEG.  However, I did spend quite a bit of time working to get the relative efficiency (i.e., energy consumed in production / total energy produced) of each type of fuel chain to make sense.  In particular, I tried to make reasonable tradeoffs between realism and game sensibility (i.e., costly processes should be more efficient).  I'm reasonably happy with where things landed.

@GnarlyOldGuy, if you're keen to check things out, please to ahead.  Otherwise, would you please just close this issue?  Thanks!
