### ISSUE TITLE
Add Forge Microblocks to the mod pack for better partial block creation and placement.

### ISSUE THREAD

**Issue by GnarlyOldGuy** [tungstonminer/brunel-3#36]
Maybe it's just because I haven't used the Chisel and Bits all that much.  I've tried to use the saw from C&B and the blocks, while similar, do not have the same placement capability and ease of use as the partial blocks created by the Forge mods.  Am I wrong on this?

**Comment by tungstonminer** [comment]
I'm not opposed to adding MicroBlock to the modpack, but I'd highly recommend you give Chisels & Bits a try as it's *much* more flexible and really not any more difficult to use (once you learn how it works).  I even did a [mod spotlight](https://www.youtube.com/watch?v=wASJl67-M6M) on it a while back.

**Comment by GnarlyOldGuy** [comment]
OK, just a suggestion.  From my limited and lazy perspective, the creation of the majority of build elements I use in my building are made with the MicroBlocks tool, quicker to create and easier to place, in my opinion.
I have used the Chisel and Bits mod for the finer elements, an example of that is at my launch site in Ad Astra.  But for the quick placement of pillars, panes, and such I think the MicroBlocks beats the Chisel and Bits.
Just my personal opinion . . . . for whatever that is worth to someone else besides me. ;)

**Comment by andrewminer** [comment]
I've added ForgeMultipart, but I still think Chisels & Bits is a better system, overall.  :-)

**Comment by tungstonminer** [comment]
I've added ForgeMultipart, but I still think Chisels & Bits is a better system overall.  Particularly if you make youself a handful of positive patterns, you can replicate blocks even more quickly than with multipart.  But, eh, each to his own.  😄
