### ISSUE TITLE
Remove PHC fruit trees which overlap with Forestry

### ISSUE THREAD

**Issue by GnarlyOldGuy** [tungstonminer/brunel-3#5]

**Comment by GnarlyOldGuy** [comment]
There are 5 trees from Pam's that overlap Forestry (lime, walnut, lemon, plum, maple), there are also 3 Minecraft trees that overlap with Forestry(jungle, acacia, dark oak).  Which has precedence?  Forestry?

**Comment by tungstonminer** [comment]
Yes, Forestry has precedence.  I'd love it if *all* the HarvestCraft trees could be "bred" in the same way as the Forestry trees, but that's just not how things work right now.  You can ignore the Forestry trees which overlap with the vanilla trees.  Those ones are trivial to produce from the vanilla variants.

**Comment by tungstonminer** [comment]
I just did a double-check (as I remember there being more than that), and I found:

apple, chestnut, cherry, date, lemon, lime, papaya, plum, walnut

All the overlapping ones from Harvestcraft have been removed.
