### ISSUE TITLE
Harvest a crop of Industrial Hemp

### ISSUE THREAD

**Issue by tungstonminer** [tungstonminer/brunel-3#50]

**Comment by GnarlyOldGuy** [comment]
OK, so I started the work on this and forgot to assign it to myself.  Here's what I found so far trying to do this in pure survival mode.

1. I think the raw materials are nerfed too much.  In real life, if I harvest a bunch of wheat do I only get a single seed from that bunch?  If I plant a dandelion seed do I only get a single seed from the one plant again?  A little too nerfed in my opinion.
2. Are the probabilities adjustable on the cross-breeding?  For plants that are important to the initial portion of gameplay, maybe the probabilities should be adjusted to enable these to happen a little more often.  I planted wheat to cross-breed and try for a more robust seed group.  Nothing for quite some time and when it did happen, bupkis, that same as the initial seeds.  When trying to cross-breed dandelion and wheat, again nothing after 5 cycles.
3. The online tutorial I watched showed the status of the plant in the crop frame when you rolled over them, it looks like the crop frame is interfering with this, can this be adjusted?

If this is one of the initial items required to move forward in the game and it's very rare to happen at the beginning, I can see people losing interest quickly.

**Comment by AndMattBurt** [comment]
On the status in waila thing, I think using the magnifying glass included in agricraft is actually a better (and more balanced) way of seeing that info.

I also think that it would be nice to get a boost (a small one) by using humas since it gives the fertilizer a reason for existing!

**Comment by tungstonminer** [comment]
> I think the raw materials are nerfed too much

I'm not 100% sure, but I think the number of seeds dropped can be configured in the Agricraft settings.  Feel free to do so.  Just open an issue to track the work.

> Are the probabilities adjustable on the cross-breeding?

Yup.  Also in the Agricraft configs.  And, likewise, feel free to open an issue and start fixing things to fit what feels balanced to you.

**Comment by GnarlyOldGuy** [comment]
> On the status in waila thing, I think using the magnifying glass included in agricraft is actually a better (and more balanced) way of seeing that info.
Yes, but you need to sneak and right-click to see the stats, something I didn't know at first.  So, I mistakenly harvested crops that I didn't want to.  Derp . . . 
Also, was finally able to get a hemp plant to mutate from dandelion and wheat, and harvest the plant, get a single piece of hemp and a seed.  I had to change the `mutation chance` in the config from 0.2 to 0.5 to get things moving a little.  Doesn't happen that fat most of the time, maybe we set this to 0.5 at the beginning of the game to let people get a leg up and then nerf it back to 0.4 or 0.3?
I'll let AMB close this out when he finishes.

**Comment by tungstonminer** [comment]
I think we talked a bit about this way back when I first gave you the mutations to work on, but I'm completely happy to have our first-level mutations be quite easy to obtain, and then make things progressively more difficult from there.  So, I propose:

* the mutation probability of a certain plant is 75% that of its least probable parent
* vanilla plants are considered to have a 100% probability for this calculation

So, that would mean that hemp has a 75% probability of mutation since both its parents are vanilla plants.  Anything which which is a direct mutation of hemp would have a 56% mutation chance (75% * 75%).  Anything mutating from that plant would have no better than a 42% chance, etc.

**Comment by AndMattBurt** [comment]
Could you use a different soil to make sure you get the mutation, not sure how it works but when I've done it before, it seems that it tries to do the seed you don't want but can't so it just takes the same time but you don't have to clear out the failed attempts... Hope that makes sense, I can try to rephrase if not

**Comment by tungstonminer** [comment]
Good question... but I don't think that's one of your options.  The mutations file doesn't know anything about the soil, and the plant file (which has the soil config) doesn't know anything about mutations.  😞

**Comment by GnarlyOldGuy** [comment]
![image](https://user-images.githubusercontent.com/51884301/108808383-601e3c00-755b-11eb-90c7-ad8c5e3f1d8a.png)
As you can see from the mutation recipe the probability is already 75% for hemp from Dandelion and Wheat.  I adjusted the mutation chance in the config file, I believe that impacts all of the mutations in the game.  This would end up being a server config, so do we want to leave this at the original 0.2 or shift it upscale slightly.
Overall it wasn't that hard to create the small farm plot, get the materials for the crop stakes, find the dandelions and wheat, get the seeds, plant them and eventually get the hemp seed needed to move forward.  Of course, the first three mutations of the dandelion/wheat combo were for the less probable corn plant?!?!
On the soil question, it only shows the farmland as an option for the mutation, it doesn't cycle to any other soil type.

**Comment by tungstonminer** [comment]
> mutation chance in the config file... impacts all of the mutations in the game

That's right.  The mutation chance in each individual mutation file is multiplied through with that value to find the final value.  I *believe* the final chance is displayed in JEI, so whatever combination gets us to the desired final numbers is fine.

> the first three mutations of the dandelion/wheat combo were for the less probable corn plant

Hmm.  My intention was *not* to have any duplicates, but I must have missed something, somewhere.  Would you please adjust the mutation to something else so there isn't a conflict?

**Comment by GnarlyOldGuy** [comment]
I can disable the corn mutation in the .json file, that the desirable route?

**Comment by AndMattBurt** [comment]
Is there another way to get corn crops? If they can be obtained from the gardens then there is no point in breeding them from wheat

**Comment by tungstonminer** [comment]
> I can disable the corn mutation in the .json file, that the desirable route?

No... we still want to be able to develop corn.  We just need a different set of parents which aren't be used by anything else.

> Is there another way to get corn crops?

No, and that's actually deliberate.  *All* of the crops which aren't vanilla plants can *only* be obtained through breeding via Agricraft deliberately.

**Comment by GnarlyOldGuy** [comment]
OK, I will look at other options for the corn mutation.

**Comment by tungstonminer** [comment]
Instead of the weird randomness the Harvestcraft garden system introduces, you just find vanilla plants growing in the wild, and then craft them into seeds.  From there, you can use Agricraft to create any other plants you want using the Agricraft system.  Unlike stock Agricraft, I made it so that *all* vanilla plants have accessible seeds, and then created a whole new system of mutations to take advantage of the greater starting options.

**Comment by tungstonminer** [comment]
> I will need to look at all the other mutations to see what fits, it might need to be a second, third or fourth generation mutation.

Sounds perfect.

**Comment by GnarlyOldGuy** [comment]
Did you update the horticulture file you created earlier?

**Comment by GnarlyOldGuy** [comment]
For TM, based on what happened yesterday with the hemp mutation, I have a follow-up question and some initial findings.

Did you intend each mutation to be unique?

For instance, a mutation of Nether Wart and White Tulip should only produce a single mutation.

I was going over the code this morning in order to create a unique mutation to build corn, and I'm finding duplicates, thus the question above.

**Comment by GnarlyOldGuy** [comment]
Besides the corn duplicate found yesterday so far I've found 2 other mutations that produce multiple results, one that has a double possibility, the other three possible results.  I'm mapping the rest now reviewing the code, bouncing back and forth between the desktop, to record the mutations, and the game is a major pain and the code is the true source.

Here are my thoughts on the mutations.  1st generation mutations are purely vanilla plants. 2nd generation mutations are between vanilla and resulting 1st generation mutations.  3rd generation mutations are anything exclusive of vanilla plants.  I'm currently mapping these out and hope to have them completed today.

**Comment by tungstonminer** [comment]
If this is going to take a lot of time, I'd say this is less important than some of the other things in the queue (particularly more of the play-testing items).  I recommend you open an issue on the issue board so we can prioritize it and get back to it.

**Comment by GnarlyOldGuy** [comment]
Created issue #86 . . .
