### ISSUE TITLE
Create a bronze ingot

### ISSUE THREAD

**Issue by tungstonminer** [tungstonminer/brunel-3#53]

**Comment by AndMattBurt** [comment]
Any reason you can use Copper Grit but not Tin Grit?

**Comment by GnarlyOldGuy** [comment]
Early game requires a furnace to make this, not sure how it was tested before.  Working in the latest version 0.4 Beta, in survival.  The materials are a little challenging, you need torches to go into caves and such to find or dig holes in the surrounding environment.  There's no recipe currently for the furnace to be able to make bronze dust to smelt in the furnace for a bronze ingot.

**Comment by GnarlyOldGuy** [comment]
Need a bronze dust recipe, TM is working on this.  Closing again.
