### ISSUE TITLE
Create a loaf of bread

### ISSUE THREAD

**Issue by tungstonminer** [tungstonminer/brunel-3#54]

**Comment by AndMattBurt** [comment]
Bread is ok to make, it needs salt which, unless there is some world gen for it, requires drying water in the cheese mold to get salt which is frustratingly slow (realistic so dont change!)

controversially the last step from dough to bread is in a crafting table with bakeware which I think ought to be an oven/furnace recipe

**Comment by tungstonminer** [comment]
> salt... world gen

The cheese mold is intended to be the way you get salt.  How much does it make?  That isn't something I have any control over (I think...), but I may choose to make changes if it's something ridiculous.

> the last step... ought to be an oven/furnace recipe

I'm right there with you!  Unfortunately, *so many* of the HC recipes are pretty much the same that I'm hesitate to start down that particular rabbit hole...

**Comment by AndMattBurt** [comment]
It makes 16 so its not terrible, still infinitely better than the old way which was just a water bucket in the crafting grid if memory serves
