### ISSUE TITLE
Cross-breed "common" bees

### ISSUE THREAD

**Issue by tungstonminer** [tungstonminer/brunel-3#55]

**Comment by GnarlyOldGuy** [comment]
What do you mean by "common?"  I was exploring and found an apiary in the village closest to my base.  There were actually two and I stole one of them, is that cheating?  I bred a princess I found in the shack chest and a drone.

**Comment by tungstonminer** [comment]
LOL... yes, that's cheating.  😆 

The goal here is whether you can:

1. find two different species of beehive out in the wild
2. create a beehouse (the most basic artificial beehive)
3. manage to run through enough generations to actually produce a Common princess

**Comment by GnarlyOldGuy** [comment]
Initially, I thought there may be too many wild beehives in the environment, I was probably wrong.

Finding the materials to build the scoop and smoker is not impossible, you just need to have access to the right biomes. (do we see a thread here?)
Building the beehouse, not a significant challenge unless you are in the desert or the tundra.
You will run through a number of generations of princesses and drones to get to a Common Princess, especially if you don't have a good set of initial princesses and drones.  I am still trying to get to the common.
A video I watched suggested that the best initial pairings were from the meadows and forest hives.  I need to grab some of these and see if it reduces the time to Common success.

Will the wild beehives respawn?  Will it be necessary?

**Comment by tungstonminer** [comment]
This is a mid-game kind of activity, so it's okay that it's a bit more challenging.  From what you're saying, everything seems to check out.

Wild beehives do *not* respawn, but I've changed things so that you sometimes get an extra princess when the queen dies.  I think that will be sufficient to avoid having to search out tons and tons of beehives.
