### ISSUE TITLE
Create a piece of charcoal

### ISSUE THREAD

**Issue by tungstonminer** [tungstonminer/brunel-3#62]

**Comment by AndMattBurt** [comment]
Creating charcoal is a little tricky due to the gating of flint and steel for the Forestry piles and Iron for the hammer from immersive eng. Maybe consider allowing the multiblock to form with another (cheaper) tool so as not to gate it so hard

**Comment by tungstonminer** [comment]
Gotcha.  So... how *did* you wind up making charcoal?  ;-)

**Comment by AndMattBurt** [comment]
I went for the coke oven since Im working on creosote for rails but I made the hammer by discarding the needed resources (may have subbed tin for Iron since thats what I had in the mines locally)

**Comment by andrewminer** [comment]
Discarding?

**Comment by AndMattBurt** [comment]
you really calling me out on this?... Yea i cheated just a little ok!

**Comment by andrewminer** [comment]
Ah...  but that defeats the purpose of the test!  I'd completely forgotten about needing an engineering hammer to even form the Coke Oven.  So, making torches (at least using the Coke Oven method) is gated on finding iron for the hammer.  Or, at least finding a village to steal a hammer from.  :-)

**Comment by AndMattBurt** [comment]
Yea, or the flint and steel for the charcoal pit

**Comment by tungstonminer** [comment]
Yup, that, too.  Hmm.  Things to ponder.

**Comment by AndMattBurt** [comment]
It will be fine when there is a pre-charcoal torch, I just didnt fancy it in my test

**Comment by GnarlyOldGuy** [comment]
I

**Comment by GnarlyOldGuy** [comment]
I cheated just a little on this one.  I dug for the flint, but the steel was a long chain development, so I used creative to get the steel to make the flint and steel.  Then I made a charcoal pit using gravel that I dug up to get the flint.  Found that you get 16 charcoal for every pile of wood.  So, four pieces of wood to make a wood stack, one wood stack yields sixteen charcoal, not a bad yield.
So early game, what can you use to start the burn for the charcoal pit?

**Comment by tungstonminer** [comment]
The Flint & Steel is actually a vanilla item, and therefore uses an Iron Ingot instead of a Steel Ingot (since steel doesn't exist in vanilla).  So, really all you need is a bit of flint and some iron.  Now, iron is a *bit* more difficult to come by (particularly if you don't happen to be close to mountain), so it's a legitimate concern that you may have some trouble making charcoal if you're unlucky.  However...

* iron ingots can almost always be found in the chest of a village smithy
* iron gravel should be fairly easy to find in the gravel of ocean and river beds
* iron gravel and even regular ore can be found on the surface of mountains

So, it may require a bit of work to find the iron ingot you need, but not at all impossible.  From there, making the Flint & Steel and charcoal pit should be pretty easy.
