### ISSUE TITLE
Evaluate metal processing

### ISSUE THREAD

**Issue by tungstonminer** [tungstonminer/brunel-3#66]
For each kind of metal, ensure you are able to perform all of the following transformations:

* crush ore to a single dust using the crushing hammer
* crush ore to two dusts using the I.E. Crusher machine
* smelt dust to an ingot
* convert 9 ingots to a block using the I.E. Metal Press
* convert an ingots to 9 nuggets using the I.E. Metal Press
* create a gear using a vanilla crafting table
* create a gear using the I.E. Metal Press
* create a plate using the engineering hammer
* create a plate using the I.E. Metal Press
* create a wire using the I.E. Metal Press (copper, aluminum, electrum, steel only)
* create a wire using the wire cutters (copper, aluminum, electrum, steel only)
* create a rod using the engineering hammer
* create a rod using the I.E. Metal Press

**Comment by AndMattBurt** [comment]
well.. smelting tin nuggets (railcraft) yields 1 ingot
thats a good start for your fixes!

(the recipe in JEI is correct but actually smelting in a furnace is 1->1 not 9->1 as per JEI

**Comment by tungstonminer** [comment]
I think we've done all of these in our server at this point.
