### ISSUE TITLE
Ensure item entities don't cluster in overly large stacks

### ISSUE THREAD

**Issue by AndMattBurt** [tungstonminer/brunel-3#72]

**Comment by AndMattBurt** [comment]
To reproduce:

Cut down a tree with more than 4 logs worth of wood

**Comment by AndMattBurt** [comment]
not sure if this is as simple a fix as the title suggests! any item that crafts more per recipe than the stack limit is going to give you a stack that can be manipulated, even dropped and picked up again without spliting

**Comment by tungstonminer** [comment]
There's a setting in Forge which controls how things clump together, so I was thinking to at least change that.  I think you may be right that there are certain other things which will just mean adjusting recipes and/or stack sizes such on a case-by-case basis.  Glass panes, for example, I think could have a larger stack size.  Feel free to keep adding specific examples you run across in this issue.
