### ISSUE TITLE
Water Mechanics

### ISSUE THREAD

**Issue by AndMattBurt** [tungstonminer/brunel-3#85]
Railcraft Siding Tank: Always generating water at about 5mb/sec
                                    The recipe needs 2 bronze plates and a slime ball (5x recipe req for multiblock)

Agricraft Tanks:  Generate water while raining
                           4 buckets storage per block (can be very large) and buckets can pull out water

Rain Tank: Generate water while raining 
                 6 iron and 8 bronze per block (each block holds 30 buckets)

Ground water pump: needs RF (2000ish/sec) to pull 500mb/sec water
                                  immense metal cost upfront is a big barrier to use (pipes to bedrock require 3 plates for 6) as well as the pump unit (a fair bit more iron)
                                   you also have to make an exposed shaft to bedrock which is a bit of a pain sometimes with lava etc

Not sure what balance you want for water but thought you might like to know that the dedicated waterworks mod you have is a costly option for something railcraft does passively 
I really would rather the space of several siding tanks over the power and metal cost of that pump!

**Comment by GnarlyOldGuy** [comment]
Sounds like the Railcraft Siding Tank needs to be nerfed if it generates water without a source attached.
I created a good size tank (2x9 blocks, 16,000 Storage) Agricraft tank out of wood for my testing farm, it's pretty well filled up from one rainfall.  Haven't had to use it yet because I need to make a sprinkler, but it's good for storage as well.  I am using a hole of water in the middle of a small planting area to supply the water now.

**Comment by tungstonminer** [comment]
Thanks for doing this homework, @AndMattBurt!

Without knowing the collection rate of the Agricraft and Forestry rain tanks, it's hard to really compare, but I'm pretty happy with these numbers.

5mB/s is not a lot of water.  It's calibrated to maintaining a few steam engines' needs, and not much more than that.  If you want an "industrial-scale" amount of water, not only do you have to provide power, but also a half-stack of metal (plus the pump itself).  But... you get 100x the water.  So, it's not just adding a few more siding tanks... it's adding a *lot* more tanks.  That feels like a pretty good balance.

**Comment by AndMattBurt** [comment]
I did some further testing and it appears that the siding is biome specific! I.e. doesn't work at all in the hotter climes of the world so may need a back-end check to make sure all the extra biomes are mapped properly

**Comment by tungstonminer** [comment]
Fortunately, we actually *don't* have any extra biomes in this modpack!

**Comment by tungstonminer** [comment]
Also... remember that the IE pump can remove water from rivers and oceans (which still have the vanilla water replacement mechanic).  So, for deserts and what-not, we'll want to make sure to route trains near a source of water so we can pump it up into the siding tanks.
